services:
  - type: web
    name: pdf-chat-app
    runtime: docker 
    buildCommand: docker build -t pdf-chat-app .
    startCommand: docker run -p $PORT:$PORT pdf-chat-app
    envVars:
      - key: COHERE_API_KEY
        sync: false
